### ISSUE TITLE
pic shape[?,28,28,1]

### ISSUE THREAD

**Issue by an1018** [nex3z/tfmobile-mnist-android#2]
@nex3z Hello!
I am puzzled which  code change pic shape from [28,28] to [1,28,28,1]?
looking forward your replay,thx!

**Comment by nex3z** [comment]
nex3z/tflite-mnist-android#7

**Comment by an1018** [comment]
@nex3z 感谢你的回复，不过我使用的是tfmobile-mnist-android，没有ByteBuffer ，我修改后代码如下，    
private float convertToGreyScale(int color) {
        return (((color >> 16) & 0xFF) + ((color >> 8) & 0xFF) + (color & 0xFF)) / 3.0f / 255.0f-0.5f;
    }

**Comment by an1018** [comment]
错误：08-19 10:33:46.428 4871-4871/com.example.myapplication E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
08-19 10:33:50.356 4871-4871/com.example.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://media/external/images/media/20 }} to activity {com.example.myapplication/com.example.myapplication.MainActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3319)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3362)
        at android.app.ActivityThread.access$1100(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at com.example.myapplication.MainActivity.onActivityResult(MainActivity.java:99)
        at android.app.Activity.dispatchActivityResult(Activity.java:5293)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3315)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3362) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by nex3z** [comment]
为啥有个 OpenCV 的报错 Cannot load info library for OpenCV

这一行干了啥
at com.example.myapplication.MainActivity.onActivityResult(MainActivity.java:99)

**Comment by an1018** [comment]
99行：用来分类 Result result = mClassifier.classify(bitmap);
bitmap是点击按钮上传的图片

**Comment by an1018** [comment]
@nex3z 
我加上下面语句后：
        if (mClassifier == null) {
            Log.e(LOG_TAG, "Classifier is not initialized");
            return;
       }
就显示“Classifier is not initialized“,请问这是什么错误，应该怎么解决呢

**Comment by nex3z** [comment]
初始化 `Classifier` 失败时，把异常打出来，就可以从日志看到具体失败原因，像[这样](https://github.com/nex3z/tfmobile-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tfmobilemnist/MainActivity.java#L69)。

**Comment by an1018** [comment]
初始化问题解决，然后分类时，我的网络输出是shape是[?,?,5991]，你的mnist.pb输出是[?,10]，那么结果result如何修改呢
private final float[] mResult = new float[CATEGORY_COUNT];

**Comment by nex3z** [comment]
[?, ?, 5991] 中的第二个 ? 维度指的是什么，如果可以将模型输出 [?, n, 5991] 给 flatten 到 [?, 5991 * n] 的形式，就可以使用[类似的代码](https://github.com/nex3z/tfmobile-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tfmobilemnist/Classifier.java#L29)来处理。

另外，对于 [?, n, 5991]  形式的输出，也可以说尝试声明 mResult 为

````java
private final float[] mResult = new float[n * 5991];
````

不过这种用法我没有试过，你可以尝试一下。

**Comment by an1018** [comment]
@nex3z 非常感谢，不过我第二个维度不是定值n，是变量，相当于mResult维度不确定，应该怎么解决呢

**Comment by nex3z** [comment]
可以试下按最大的尺寸申请 mResult 的长度，看能不能运行起来。不确定 TensorFlow Mobile 是否支持这种用法。
